### PR TITLE
upgrade to dnx latest bits

### LINKED ISSUE #5: Upgrade to DNX
Based on dnx v1.0.0-beta4-11532.

### PR DESCRIPTION
**Pull request by luisrudge**

### CODE REVIEW

**Comment by luisrudge** [comment]
this fixes #5

**Comment by luisrudge** [comment]
Also, we should rename this project :D

**Comment by tugberkugurlu** [comment]
Sweet! Thanks @luisrudge! Pushing the new version in a bit.

**Comment by tugberkugurlu** [comment]
@luisrudge pushed the new version but npm gallery cache is stupid :smile: haven't appeared yet https://www.npmjs.com/package/gulp-aspnet-k

**Comment by luisrudge** [comment]
Awesome! What about renaming the project? :)

**Pull request merged**
