### PR TITLE
allow changing cwd (current working directory)

### PR DESCRIPTION
**Pull request by luisrudge**
I'm working on a project that has this structure:

```
./
  ./client
  ./server
gulpfile.js
```

Because of that, I had to change the cwd. As soon as you merge that (if you want to), I'll publish my yeoman-generator with that. Thanks!

ps: you had some tab/spaces inconsistencies. I untabified everything. Let me know if you prefer tabs.

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
thx! Looks good to me.

**Comment by luisrudge** [comment]
Great. Thanks!

**Comment by luisrudge** [comment]
@tugberkugurlu can you push a new version to npm? Thanks!

**Comment by tugberkugurlu** [comment]
Damn, forgot that :sadpanda: I will do it soon today.

**Comment by luisrudge** [comment]
Ok. Let met know when. Thanks

**Comment by luisrudge** [comment]
Have you published?

**Comment by tugberkugurlu** [comment]
@luisrudge done, published: https://www.npmjs.com/package/gulp-aspnet-k. Sorry about the delay :cry:

**Comment by luisrudge** [comment]
@tugberkugurlu awesome thanks!

**Pull request merged**
