### PR TITLE
renaming k to dnx

### LINKED ISSUE #9: rename
so, should we rename to gulp-dnx or gulp-aspnet-dnx? :)

### PR DESCRIPTION
**Pull request by luisrudge**
fix #9

### CODE REVIEW

**Comment by luisrudge** [comment]
Maybe we should rename to gulp-dnx? Not sure the aspnet work will last for long

**Comment by tugberkugurlu** [comment]
Yes, correct. Good though.

It can be dnx only but we also have some web specific stuff like calling web command by default.

If we can remove those conventions, why not. What do u think?

**Comment by luisrudge** [comment]
I already removed the web command. no the `dnxCommand is required`

**Comment by tugberkugurlu** [comment]
Ah, cool! Yes, gulp-dnx seems better than. Do you want to update it accordingly?

**Comment by luisrudge** [comment]
Yep. We'll do it today

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by luisrudge** [comment]
@tugberkugurlu Let me know when you review this. I changed the dnxCommand to be the first parameter of the function. It's all in the readme.

**Comment by luisrudge** [comment]
any news? :)

**Comment by tugberkugurlu** [comment]
Damn, busy days :s on my phone now but will look at it and merge it in about two hours :smile: sorry for the delay :s

**Comment by luisrudge** [comment]
no problem. I want to fix the other problem too but I need this merged: https://github.com/npm/npm/issues/8359#issuecomment-106572853

**Pull request merged**
