### PR TITLE
Updated the run command to be multi-platform aware

### PR DESCRIPTION
**Pull request by johnrizzo1**
I updated gulp-dnx so that it will run on unix and windows platforms.  I tested this on Windows, Linux and MacOS but not on anything else.

### CODE REVIEW

**Comment by luisrudge** [comment]
I like this! Can you please fix the tabs/spaces issue so I can merge it?

**Comment by johnrizzo1** [comment]
Updating it now.

**Comment by johnrizzo1** [comment]
@luisrudge, what is the standard?  4 spaces?

**Comment by johnrizzo1** [comment]
@luisrudge I think I fixed the spacing issue.  Let me know if this is ok to merge.

**Comment by luisrudge** [comment]
Yesssssssss! Perfect!

**Comment by luisrudge** [comment]
@johnrizzo1 I just published to npm! Thanks! Merry Christmas! :)

**Comment by johnrizzo1** [comment]
Thank you.  Happy Holidays ;)

-- 
John

On December 24, 2015 at 12:00:15 AM, Luís Rudge (notifications@github.com) wrote:

@johnrizzo1 I just published to npm! Thanks! Merry Christmas! :)

**Pull request merged**
